spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8080/dbqis
    username: root
    password:
jpa:
  hibernate.ddl-auto: update
  generate-ddl: true
  show-sql: true